#!/bin/bash

# Shell script prepares the minlog app bin/ directory structure, recreating
# after git clone operation


mesgstr="Made"

if [[ $(basename $PWD) != "minlog" ]]
then
  echo "$(basename $0) must be run from the base directory of the minlog app"
  exit 1
fi

# check for directories, make non-existant
if [[ ! -d "bin" ]]
then
  mkdir bin
  mesgstr="$mesgstr bin"
fi

if [[ ! -d "bin/classes" ]]
then
  mkdir bin/classes
  mesgstr="$mesgstr bin/classes"
fi

if [[ ! -d "bin/funct" ]]
then
  mkdir bin/funct
  mesgstr="$mesgstr bin/funct"
fi

if [[ ! -d "bin/objects" ]]
then
  mkdir bin/objects
  mesgstr="$mesgstr bin/objects"
fi

if [[ ! -d "bin/tests" ]]
then
  mkdir bin/tests
  mesgstr="$mesgstr bin/tests"
fi

# print result message
if [[ "$mesgstr" == "Made" ]]
then
  echo "bin/ directories present"
else
  echo "$mesgstr directories"
fi
