#!/bin/bash

HEADER_TEMPLATE=~/OffBrand/scripts/templates/PublicHeader.h
RESTRICTED_TEMPLATE=~/OffBrand/scripts/templates/PrivateHeader.h
SOURCE_TEMPLATE=~/OffBrand/scripts/templates/Source.c

function print_usage() {
  echo "Usage:"
  echo "$(basename $0) [class name]"
  echo
  echo "Script generates new files for a OffBrand compatible class with the"
  echo "specified name. All code required for reference counting and inclusion"
  echo "in OffBrand container structures is in place. The user must add"
  echo "relevant thread safety procedures and functionallity specific to the"
  echo "class created."
  echo
  echo "[class name] should not have any file extensions"
  echo
  echo "See README for more information on OffBrand library"
}

#check usage
if [[ $# -ne 1 ]]
then
  print_usage
  exit 1
fi

if [[ $1 == "-h" ]] || [[ $1 == "--help" ]]
then
  print_usage
  exit 0
fi

#Generate substitution strings
codeClassName=$1
macroClassName=$(echo $1 | tr '[a-z]' '[A-Z]') #capitalize class name

#filenames
publicHeader=$codeClassName".h"
privateHeader=$codeClassName"_Private.h"
sourceFile=$codeClassName".c"


#substitute class name into template files and write files with proper file
#names to the current directory
cat $HEADER_TEMPLATE | sed "s/%CODECLASSNAME%/$codeClassName/g" | \
  sed "s/%MACROCLASSNAME%/$macroClassName/g" > $publicHeader
echo "$publicHeader created"

cat $RESTRICTED_TEMPLATE | sed "s/%CODECLASSNAME%/$codeClassName/g" | \
  sed "s/%MACROCLASSNAME%/$macroClassName/g" > $privateHeader
echo "$privateHeader created"

cat $SOURCE_TEMPLATE | sed "s/%CODECLASSNAME%/$codeClassName/g" | \
  sed "s/%MACROCLASSNAME%/$macroClassName/g" > $sourceFile
echo "$sourceFile created"

echo ""
echo "New class created, ready for editing"
