#!/bin/bash

# Shell script prepares the offbrand library bin/ directory structure,
# which needs to be recreated after cloning in git


mesgstr="Made"

# check for directories, make non-existant
if [[ ! -d "bin" ]]
then
  mkdir bin
  mesgstr="$mesgstr bin"
fi

if [[ ! -d "bin/objects" ]]
then
  mkdir bin/objects
  mesgstr="$mesgstr bin/objects"
fi

if [[ ! -d "bin/tests" ]]
then
  mkdir bin/tests
  mesgstr="$mesgstr bin/tests"
fi

# print result message
if [[ "$mesgstr" == "Made" ]]
then
  echo "bin/ directories present"
else
  echo "$mesgstr directories"
fi
